### ISSUE TITLE
Re-organize image list

### ISSUE THREAD

**Issue by bayazidbh** [ublue-os/website#281]
https://universal-blue.org/images

Currently, this is what the image list looks like:

![image](https://github.com/ublue-os/website/assets/26621899/fe01d514-4036-4780-b32a-93d782b64a4d)

The images are only organized by alphabet, leading to a situation where the experimental bazzite is on the top, the cosign keypair image is just somewhere in the middle of the list, and overall the list having no guidance for what a user might want beyond just scrolling or use Find in Page until they found what they need -- and I don't think ublue will stop releasing new image editions.

I agree with @castrojo that it should probably be automated in some way not only for sustainability but because it is in-line with ublue-os mission, but there should also be a better structure for it.

My proposal is for the image list to be separated to two main categories:

- Curated Experiences: this is for bluefin, beyond, bazzite, and any other images with custom/opinionated experience that ublue have.
- Desktop Variants: this is like Vauxite and Kinoite where the experience is otherwise somewhat vanilla based on the upstream DE / Fedora image.

And for both categories: 

- Separate each DE variants / editions with a MkDocs Content Tabs. 
- Then, further separate Intel/AMD and Nvidia images with tabs if possible, or just with lists if not.
- Ideally some sort of Collapsible Block to explain the most important part that is added to the images - or at the very least a link to the repo where they can read the full explanations for the images.

(speaking personally, I didn't get what "batteries included" meant as a non-native speaker)

From my understanding of ublue-scan process, it seems to pull from the image labels/description? My suggestion is to put append a `Part of Universal Blue {Curated Experience/Desktop Variants}, this image is meant for system with {Intel and AMD/Nvidia} graphics.` inside the image label that should be easy enough to grep into ublue-scan elements, but still English-readable for others who may encounter the image label through artifacthub or search engines.

On the other hand, if there's a simple way to submit new images to the list or we could in some way make sure that it will remain updated, perhaps it might be worth it to make it a manually created page instead?

**Comment by marcoceppi** [comment]
> The images are only organized by alphabet, leading to a situation where the experimental bazzite is on the top, the cosign keypair image is just somewhere in the middle of the list, and overall the list having no guidance for what a user might want beyond just scrolling or use Find in Page until they found what they need -- and I don't think ublue will stop releasing new image editions.

There is definitely a growing need to better organize images. I know there's been different concepts on how that could be organized done already and any one of them is a fine approach. What I see from your proposal is really two categories: Universal Blue "Base" (I use this loosely, but you've referred to them as Desktop Variants) and for lack of a better word "distros" (what you refer to as Curated Experiences). I wanted to draw a distinction about base and distro (yes, we are not a distro - but) because I don't think most people will use the "vanilla", or "base", images. People will instead either end up gravitating towards one of the curated experiences or making their own curated experience.

Conveying that in a re-organized image list feels more important than saying "these are gnome images". I don't have a good opinion on /how/ to convey that but wanted to share my support for your delineation while adding some additional personal feelings on the subject.

> And for both categories:
> Separate each DE variants / editions with a MkDocs Content Tabs. Then, further separate Intel/AMD and Nvidia images with tabs if possible, or just with lists if not. Ideally some sort of Collapsible Block to explain the most important part that is added to the images - or at the very least a link to the repo where they can read the full explanations for the images.

We use mkdocs and we are the ones that generate the image list and the markdown for it. There's no limitations at all to what we can generate including embedding pure/raw HTML. This shouldn't be viewed as a limitation to only markdown that's supported in mkdocs - it was done that way to date for speed and ease. Markdown, and by extension mkdocs, fully supports HTML (css, js, etc) inside of a `.md` file.

> From my understanding of ublue-scan process, it seems to pull from the image labels/description? My suggestion is to put append a Part of Universal Blue {Curated Experience/Desktop Variants}, this image is meant for system with {Intel and AMD/Nvidia} graphics. inside the image label that should be easy enough to grep into ublue-scan elements, but still English-readable for others who may encounter the image label through artifacthub or search engines.

The ublue-scan process reads the description container label but can also read any additional labels. In my experience enforcing text patterns for lookups can be tricky and limiting we could - using your example of curated/desktp and Nvidia additional custom labels can be added to images to delineate those qualities:

```
org.universal-blue.gpu-enablement={nvidia,amd,...}
org.universal-blue.category={curated,desktop}
```

While they won't be directly exposed on artifacthub, artifacthub does embed the README from the repos where the image author would have the opportunity to explain the difference variances available for their image.

> On the other hand, if there's a simple way to submit new images to the list or we could in some way make sure that it will remain updated, perhaps it might be worth it to make it a manually created page instead?

I'm pretty against a manual process. One of this projects goals is to remove and avoid toil and hand editing a list of images and their categorization feels to me like toil. There is already a small curation process where images can be blocked from being auto generated and I wouldn't want to expand upon that.
