### ISSUE TITLE
404 - https://universal-blue.org/images/main.md

### ISSUE THREAD

**Issue by alexsch01** [ublue-os/website#394]
![image](https://github.com/ublue-os/website/assets/5721147/a96e3b91-2d13-4fb6-a5e3-f110f97a2201)

**Comment by alexsch01** [comment]
also this for https://universal-blue.org/images/main/

Missing sidebar

![image](https://github.com/ublue-os/website/assets/5721147/093c3695-4a9e-4e85-b5ce-46ead9889a9d)

**Comment by storyaddict** [comment]
Is this just in the wrong place @castrojo 

![image](https://github.com/ublue-os/website/assets/55410594/95961101-7b66-4f36-9787-f3cf59c9c006)

**Comment by storyaddict** [comment]
Also, thanks @alexsch01 for reporting this.

**Comment by castrojo** [comment]
I am pretty sure we need to fix it in the config file: https://github.com/ublue-os/website/blob/main/mkdocs.yml

Getting that thing right so that our menus actually make sense has alluded me so far. If you could figure out how to make them make sense in general it'd really remove a ton of confusion from the site.

**Comment by storyaddict** [comment]
I'm going to really dig into this tomorrow and try reorganizing the site to make it clearer.

**Comment by alexsch01** [comment]
Thanks @storyaddict, it's fixed now
