### ISSUE TITLE
Add a features page

### ISSUE THREAD

**Issue by flexagoon** [ublue-os/website#724]
With the removal of the images page, [this page](https://universal-blue.org/images/main/#Features) which lists all of the differences between uBlue and upstream Silverblue is no longer available. I think this information should be added somewhere else in that case, as I referred to that page pretty regularly.

Also, perhaps a slightly unrelated question, but why was the images page even removed? I saw #712, but I don't understand the decision of the main uBlue images not being "end user products" - I think "Silverblue but pre-configured" is a very useful image for end users who don't want to add all the extra bloat and customization of Bluefin.

**Comment by nicknamenamenick** [comment]
We were discussing the state of this website yesterday.  It eventually needs to be redesigned, but we're not sure how that will work out yet.  We may use our [Discourse](https://universal-blue.discourse.group/) to fill the needs that this website once served.

As for the images page, anyone can still consume and use the main images.  We can't tell anyone what to do, but we would prefer if new users used Bazzite, Bluefin, and maybe a couple of other end-user focused images in the future.  The images page is also hidden here: https://universal-blue.org/images/ 

Several points were made yesterday about this as well:
- Implication that Fedora is an unfinished product because the minor changes we have done with our main images make it a "better Fedora" which isn't true.  
  - We added some extra packages and supported RPMFusion out of the box, and that's only a small part of our vision for a desktop operating system.
  - We do not want to compete with Fedora Atomic.
- We do not want support tickets for the main images because we are not adding new features that are already in either Bluefin or Bazzite.
  - The main images should not stray too far away from upstream so we will not be "fixing" things like removing the Firefox RPM from the image unless upstream eventually does this themselves.

We do not want to pay for hosting our main images' ISOs as each variant will need a previous Fedora release, current release, Nvidia variant, and other hardware variants on top of that.  It's not worth it when we would prefer to promote operating systems that are already fleshed out like Bluefin and Bazzite that work beyond the "Fedora with tweaks" ideology.

We're exploring other options like having users generate local ISOs based on their current deployment, and there is also the [Blue-Build project](https://blue-build.org/) which is the continuation and revamp of our old Startingpoint method for creating your own custom Fedora images.

Anyone can still rebase to the main images.  We still use them to create our end-user focused ones, so they will always be supported in a sense with updates, but not so much technical support or feature requests for them. I understand that several individuals, including myself, started with the main images since our end-user focused ones didn't exist or were in heavy development.  We do not plan to make new offline ISOs for them, but rebasing should always work for them.  The outcome of the new Universal Blue website, whatever that may be, will most likely not promote the main images for daily usage.

**Comment by castrojo** [comment]
> very useful image for end users who don't want to add all the extra bloat and customization of Bluefin.

If 500MB is "bloat" to you then you'll know where to find the base images.

**Comment by castrojo** [comment]
https://universal-blue.org/scope/?h=main#main-images is where the feature list is.
